"""simple-shaped core tables

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 21:50:37.123336
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('facility_type', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('facility_size', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('registration_facility_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registration_facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('age_updated_at', sa.DateTime(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reminder_consent', sa.String(), nullable=False),
    sa.Column('registration_facility_id', sa.UUID(), nullable=False),
    sa.Column('assigned_facility_id', sa.UUID(), nullable=False),
    sa.Column('registration_user_id', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['registration_facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['registration_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_patients_on_assigned_facility_id', 'patients', ['assigned_facility_id'], unique=False)
    op.create_index('index_patients_on_recorded_at', 'patients', ['recorded_at'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('street_address', sa.String(), nullable=True),
    sa.Column('village_or_colony', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_addresses_on_patient_id', 'addresses', ['patient_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('creation_facility_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cancel_reason', sa.String(), nullable=True),
    sa.Column('remind_on', sa.Date(), nullable=True),
    sa.Column('agreed_to_visit', sa.Boolean(), nullable=True),
    sa.Column('appointment_type', sa.String(), nullable=False),
    sa.Column('device_created_at', sa.DateTime(), nullable=False),
    sa.Column('device_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creation_facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_appointments_on_facility_id', 'appointments', ['facility_id'], unique=False)
    op.create_index('index_appointments_on_patient_id_and_scheduled_date', 'appointments', ['patient_id', 'scheduled_date'], unique=False)
    op.create_index('index_appointments_on_scheduled_date', 'appointments', ['scheduled_date'], unique=False)
    op.create_table('blood_pressures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=False),
    sa.Column('diastolic', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_blood_pressures_on_facility_id', 'blood_pressures', ['facility_id'], unique=False)
    op.create_index('index_blood_pressures_on_patient_id_and_recorded_at', 'blood_pressures', ['patient_id', 'recorded_at'], unique=False)
    op.create_index('index_blood_pressures_on_recorded_at', 'blood_pressures', ['recorded_at'], unique=False)
    op.create_table('blood_sugars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blood_sugar_type', sa.String(), nullable=False),
    sa.Column('blood_sugar_value', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_blood_sugars_on_patient_id_and_recorded_at', 'blood_sugars', ['patient_id', 'recorded_at'], unique=False)
    op.create_table('medical_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('hypertension', sa.String(), nullable=False),
    sa.Column('diabetes', sa.String(), nullable=False),
    sa.Column('prior_heart_attack', sa.String(), nullable=False),
    sa.Column('prior_stroke', sa.String(), nullable=False),
    sa.Column('chronic_kidney_disease', sa.String(), nullable=False),
    sa.Column('receiving_treatment_for_hypertension', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_medical_histories_on_patient_id', 'medical_histories', ['patient_id'], unique=False)
    op.create_table('patient_phone_numbers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('phone_type', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('dnd_status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_patient_phone_numbers_on_patient_id', 'patient_phone_numbers', ['patient_id'], unique=False)
    op.create_table('prescription_drugs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rxnorm_code', sa.String(), nullable=True),
    sa.Column('dosage', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('is_protocol_drug', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('device_created_at', sa.DateTime(), nullable=False),
    sa.Column('device_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_prescription_drugs_on_patient_id', 'prescription_drugs', ['patient_id'], unique=False)
    op.create_table('call_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('result_type', sa.String(), nullable=False),
    sa.Column('remove_reason', sa.String(), nullable=True),
    sa.Column('device_created_at', sa.DateTime(), nullable=False),
    sa.Column('device_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_call_results_on_appointment_id', 'call_results', ['appointment_id'], unique=False)
    op.create_index('index_call_results_patient_id_and_updated_at', 'call_results', ['patient_id', 'device_updated_at'], unique=False)
    op.create_table('communications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('communication_type', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=True),
    sa.Column('device_created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_communications_on_appointment_id', 'communications', ['appointment_id'], unique=False)
    op.create_index('index_communications_on_patient_id', 'communications', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_communications_on_patient_id', table_name='communications')
    op.drop_index('index_communications_on_appointment_id', table_name='communications')
    op.drop_table('communications')
    op.drop_index('index_call_results_patient_id_and_updated_at', table_name='call_results')
    op.drop_index('index_call_results_on_appointment_id', table_name='call_results')
    op.drop_table('call_results')
    op.drop_index('index_prescription_drugs_on_patient_id', table_name='prescription_drugs')
    op.drop_table('prescription_drugs')
    op.drop_index('index_patient_phone_numbers_on_patient_id', table_name='patient_phone_numbers')
    op.drop_table('patient_phone_numbers')
    op.drop_index('index_medical_histories_on_patient_id', table_name='medical_histories')
    op.drop_table('medical_histories')
    op.drop_index('index_blood_sugars_on_patient_id_and_recorded_at', table_name='blood_sugars')
    op.drop_table('blood_sugars')
    op.drop_index('index_blood_pressures_on_recorded_at', table_name='blood_pressures')
    op.drop_index('index_blood_pressures_on_patient_id_and_recorded_at', table_name='blood_pressures')
    op.drop_index('index_blood_pressures_on_facility_id', table_name='blood_pressures')
    op.drop_table('blood_pressures')
    op.drop_index('index_appointments_on_scheduled_date', table_name='appointments')
    op.drop_index('index_appointments_on_patient_id_and_scheduled_date', table_name='appointments')
    op.drop_index('index_appointments_on_facility_id', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('index_addresses_on_patient_id', table_name='addresses')
    op.drop_table('addresses')
    op.drop_index('index_patients_on_recorded_at', table_name='patients')
    op.drop_index('index_patients_on_assigned_facility_id', table_name='patients')
    op.drop_table('patients')
    op.drop_table('users')
    op.drop_table('facilities')
    # ### end Alembic commands ###
