"""risk scores

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26 22:25:07.015365
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('p_missed', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('band', sa.String(), nullable=False),
    sa.Column('basis', sa.String(), nullable=False),
    sa.Column('group_size', sa.Integer(), nullable=False),
    sa.Column('group_level', sa.String(), nullable=True),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_risk_scores_on_appointment_id_and_scored_at', 'risk_scores', ['appointment_id', 'scored_at'], unique=False)
    op.create_index('index_risk_scores_on_facility_id_and_scheduled_date', 'risk_scores', ['facility_id', 'scheduled_date'], unique=False)
    # ### end Alembic commands ###
    op.execute("""
        CREATE OR REPLACE VIEW latest_risk_scores AS
        SELECT DISTINCT ON (r.appointment_id) r.*
        FROM risk_scores r
        ORDER BY r.appointment_id, r.scored_at DESC
    """)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS latest_risk_scores")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_risk_scores_on_facility_id_and_scheduled_date', table_name='risk_scores')
    op.drop_index('index_risk_scores_on_appointment_id_and_scored_at', table_name='risk_scores')
    op.drop_table('risk_scores')
    # ### end Alembic commands ###
